Adds default .formatter.exs and runs `mix format` on the repo
khusnetdinov/phoenix_gon pull request #25
Opened 2018-11-01 10:19 UTC by percygrunwald

2018-11-01 11:24 UTC, khusnetdinov commented
@percygrunwald,  Could you please, create Issue and explain detailed that you try to do in this PR?

2018-11-01 11:33 UTC, khusnetdinov requested changes
This PR could be relate to 2 problems:
* Formatter input
* Editing code style.

Could you provide an example for this formater and add it to Readme?
Divide into 2 PRs. Code style would be great check with elixir code styles linters.

2019-01-23 09:13 UTC, percygrunwald commented
Hi @khusnetdinov, so sorry, I missed this comment because my GH notification preferences were all wrong. Thanks for your feedback, but I'm not sure I understand why splitting into 2 PRs makes sense.

Having a `.formatter.exs` without running `mix format` on the code seems kind of redundant, since the two go hand-in-hand.

The `mix format` (and `.formatter.exs`) has been a standard part of Elixir since 1.6, so I don't think having an example in the README is necessary. I would say most Elixir developers are familiar with running `mix format` nowadays (https://hexdocs.pm/mix/Mix.Tasks.Format.html#formatter_opts_for_file/2).

Let me know what you think. Happy to resubmit another PR.

2019-01-23 10:12 UTC, khusnetdinov approved these changes

2019-01-23 10:13 UTC, merged